/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedStudioRouteRouteImport } from './routes/_authenticated/_studio/route'
import { Route as YoutubeCallbackRouteImport } from './routes/youtube.callback'
import { Route as AuthenticatedStudioAdminRouteImport } from './routes/_authenticated/_studio/admin'
import { Route as AuthenticatedStudioDashboardRouteImport } from './routes/_authenticated/_studio/dashboard'
import { Route as AuthenticatedStudioSettingsRouteImport } from './routes/_authenticated/_studio/settings'
import { Route as AuthenticatedStudioProjectsIndexRouteImport } from './routes/_authenticated/_studio/projects.index'
import { Route as AuthenticatedStudioProjectsProjectIdRouteImport } from './routes/_authenticated/_studio/projects.$projectId'
import { Route as ApiPublicPaddleWebhookRouteImport } from './routes/api/public/paddle.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioRouteRoute =
  AuthenticatedStudioRouteRouteImport.update({
    id: '/_studio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const YoutubeCallbackRoute = YoutubeCallbackRouteImport.update({
  id: '/youtube/callback',
  path: '/youtube/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioAdminRoute =
  AuthenticatedStudioAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioDashboardRoute =
  AuthenticatedStudioDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioSettingsRoute =
  AuthenticatedStudioSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioProjectsIndexRoute =
  AuthenticatedStudioProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioProjectsProjectIdRoute =
  AuthenticatedStudioProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const ApiPublicPaddleWebhookRoute = ApiPublicPaddleWebhookRouteImport.update({
  id: '/api/public/paddle/webhook',
  path: '/api/public/paddle/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/youtube/callback': typeof YoutubeCallbackRoute
  '/admin': typeof AuthenticatedStudioAdminRoute
  '/dashboard': typeof AuthenticatedStudioDashboardRoute
  '/settings': typeof AuthenticatedStudioSettingsRoute
  '/projects/$projectId': typeof AuthenticatedStudioProjectsProjectIdRoute
  '/api/public/paddle/webhook': typeof ApiPublicPaddleWebhookRoute
  '/projects/': typeof AuthenticatedStudioProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/youtube/callback': typeof YoutubeCallbackRoute
  '/admin': typeof AuthenticatedStudioAdminRoute
  '/dashboard': typeof AuthenticatedStudioDashboardRoute
  '/settings': typeof AuthenticatedStudioSettingsRoute
  '/projects/$projectId': typeof AuthenticatedStudioProjectsProjectIdRoute
  '/api/public/paddle/webhook': typeof ApiPublicPaddleWebhookRoute
  '/projects': typeof AuthenticatedStudioProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/_studio': typeof AuthenticatedStudioRouteRouteWithChildren
  '/youtube/callback': typeof YoutubeCallbackRoute
  '/_authenticated/_studio/admin': typeof AuthenticatedStudioAdminRoute
  '/_authenticated/_studio/dashboard': typeof AuthenticatedStudioDashboardRoute
  '/_authenticated/_studio/settings': typeof AuthenticatedStudioSettingsRoute
  '/_authenticated/_studio/projects/$projectId': typeof AuthenticatedStudioProjectsProjectIdRoute
  '/api/public/paddle/webhook': typeof ApiPublicPaddleWebhookRoute
  '/_authenticated/_studio/projects/': typeof AuthenticatedStudioProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/youtube/callback'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/projects/$projectId'
    | '/api/public/paddle/webhook'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/youtube/callback'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/projects/$projectId'
    | '/api/public/paddle/webhook'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/_studio'
    | '/youtube/callback'
    | '/_authenticated/_studio/admin'
    | '/_authenticated/_studio/dashboard'
    | '/_authenticated/_studio/settings'
    | '/_authenticated/_studio/projects/$projectId'
    | '/api/public/paddle/webhook'
    | '/_authenticated/_studio/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  YoutubeCallbackRoute: typeof YoutubeCallbackRoute
  ApiPublicPaddleWebhookRoute: typeof ApiPublicPaddleWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_studio': {
      id: '/_authenticated/_studio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedStudioRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/youtube/callback': {
      id: '/youtube/callback'
      path: '/youtube/callback'
      fullPath: '/youtube/callback'
      preLoaderRoute: typeof YoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_studio/admin': {
      id: '/_authenticated/_studio/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedStudioAdminRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/_studio/dashboard': {
      id: '/_authenticated/_studio/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedStudioDashboardRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/_studio/settings': {
      id: '/_authenticated/_studio/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedStudioSettingsRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/_studio/projects/': {
      id: '/_authenticated/_studio/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedStudioProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/_studio/projects/$projectId': {
      id: '/_authenticated/_studio/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedStudioProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/api/public/paddle/webhook': {
      id: '/api/public/paddle/webhook'
      path: '/api/public/paddle/webhook'
      fullPath: '/api/public/paddle/webhook'
      preLoaderRoute: typeof ApiPublicPaddleWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedStudioRouteRouteChildren {
  AuthenticatedStudioAdminRoute: typeof AuthenticatedStudioAdminRoute
  AuthenticatedStudioDashboardRoute: typeof AuthenticatedStudioDashboardRoute
  AuthenticatedStudioSettingsRoute: typeof AuthenticatedStudioSettingsRoute
  AuthenticatedStudioProjectsProjectIdRoute: typeof AuthenticatedStudioProjectsProjectIdRoute
  AuthenticatedStudioProjectsIndexRoute: typeof AuthenticatedStudioProjectsIndexRoute
}

const AuthenticatedStudioRouteRouteChildren: AuthenticatedStudioRouteRouteChildren =
  {
    AuthenticatedStudioAdminRoute: AuthenticatedStudioAdminRoute,
    AuthenticatedStudioDashboardRoute: AuthenticatedStudioDashboardRoute,
    AuthenticatedStudioSettingsRoute: AuthenticatedStudioSettingsRoute,
    AuthenticatedStudioProjectsProjectIdRoute:
      AuthenticatedStudioProjectsProjectIdRoute,
    AuthenticatedStudioProjectsIndexRoute:
      AuthenticatedStudioProjectsIndexRoute,
  }

const AuthenticatedStudioRouteRouteWithChildren =
  AuthenticatedStudioRouteRoute._addFileChildren(
    AuthenticatedStudioRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedStudioRouteRoute: typeof AuthenticatedStudioRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedStudioRouteRoute: AuthenticatedStudioRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  YoutubeCallbackRoute: YoutubeCallbackRoute,
  ApiPublicPaddleWebhookRoute: ApiPublicPaddleWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
